fusion/urls.py
from django.conf.urls import url
from . import views

app_name = 'fusion'

urlpatterns = [
    # fusion/
    url(r'^$', views.index, name='index'),

    # fusion/login/
    url(r'^login$', views.login, name='login'),

    # fusion/leave/<pk>/
    url(r'^leave/(?P<emp_id>[0-9]+)$', views.leave, name='leave'),

    # fusion/visitorhostel/<pk>/
    url(r'^visitorhostel/(?P<emp_id>[0-9]+)$', views.visitorhostel, name='visitorhostel'),

    # fusion/placement/<pk>/
    url(r'^placement/(?P<emp_id>[0-9]+)$', views.placement, name='placement'),

    # fusion/profile/<pk>/
    url(r'^profile/(?P<emp_id>[0-9]+)$', views.profile, name='profile'),

    # fusion/phc/<pk>/
    url(r'^phc/(?P<emp_id>[0-9]+)$', views.phc, name='phc'),

    # fusion/dashboard/<pk>/
    url(r'^dashboard/(?P<emp_id>[0-9]+)$', views.dashboard, name='dashboard'),

    # fusion/temp$/
    url(r'^temp$', views.temp, name='temp'),

]

newProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('fusion.urls')),
    url(r'^fusion/', include('fusion.urls')),
]

fusion/models.py
from django.db import models
from django.core.urlresolvers import reverse

# TODO: These lists are not complete fully!

LEAVETYPE = (
    ('CL', 'Casual Leave'),
    ('COL', 'Commuted Leave'),
    ('EL', 'Earned Leave'),
    ('RH', 'Restricted Holiday'),
    ('SCL', 'Special Casual Leave'),
    ('VL', 'Vacation Leave'),
)

DESIGNATION = (
    ('driver', 'Driver'),
    ('ja', 'Junior Assistant'),
    ('sa', 'Senior Assistant'),
    ('jt', 'Junior Technician'),
    ('st', 'Senior Technician'),
    ('ar', 'Assistant Registrar'),
    ('dr', 'Deputy Registrar'),
    ('rr', 'Registrar'),
    ('Research Engineer', 'Research Engineer'),
    ('Assistant Professor', 'Assistant Professor'),
    ('Associate Professor', 'Associate Professor'),
    ('Professor', 'Professor'),
)

DEPARTMENT = (
    ('iwd', 'IWD'),
    ('et', 'Establishment'),
    ('library', 'Library'),
    ('pc', 'Placement Cell'),
    ('acad', 'Academics'),
    ('ns', 'Natural Science'),
    ('cse', 'CSE'),
    ('ece', 'ECE'),
    ('me', 'ME'),
    ('otd', 'Office of Dean'),
    ('fna', 'Finance and Accounts'),
    ('directorate', 'Directorate'),
)

AUTHDESIGNATION = (
    ('rr', 'Registrar'),
    ('director', 'Director'),
    ('ccc', 'Coordinator Computer Center'),
    ('wi', 'Workshop In-charge'),
    ('headns', 'HOD NS'),
    ('hodcse', 'HOD CSE'),
    ('hodece', 'HOD ECE'),
    ('hodme', 'HOD ME'),
    ('deanacad', 'Dean Academics'),
    ('deanstudents', 'Dean Students'),
    ('deanRSPC', 'Dean RSPC'),
)


class Employee(models.Model):
    empFirstName = models.CharField(max_length=36)
    empLastName = models.CharField(max_length=36)
    empEmail = models.CharField(max_length=36, unique=True)
    empPassword = models.CharField(max_length=36, null=False, default='pass')
    empDesignation = models.CharField(max_length=36, choices=DESIGNATION)
    empDepartment = models.CharField(max_length=36, choices=DEPARTMENT)

    def __str__(self):
        return self.empFirstName + "." + self.empLastName + "." + self.empEmail + "." + self.empPassword + "." + self.empDesignation + "." + self.empDepartment


class EmployeeLeaveBalance(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    empCL = models.IntegerField()
    empCOL = models.IntegerField()
    empEL = models.IntegerField()
    empRH = models.IntegerField()
    empSCL = models.IntegerField()
    empVL = models.IntegerField()


class EmployeeLeaveDetails(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    empLeaveType = models.CharField(max_length=5)
    empLeaveFrom = models.DateField()
    empLeaveTo = models.DateField()
    empLeaveDuration = models.IntegerField()
    empLeaveStatus = models.IntegerField(default=0)
    # Rejected: -1, Approved: 1, Pending: 0


class EmployeeStationLeave(models.Model):
    empLeaveID = models.ForeignKey(EmployeeLeaveDetails, on_delete=models.CASCADE)
    empStationLeave = models.BooleanField(default=False)
    empStationAddress = models.CharField(max_length=150)


class EmployeeLeaveAuthority(models.Model):
    authID = models.IntegerField(primary_key=True, auto_created=True)
    authDesignation = models.CharField(max_length=18, choices=AUTHDESIGNATION)
    authHeadID = models.ForeignKey(Employee, related_name='ELA_authHeadID')
    authActingID = models.ForeignKey(Employee, null=True, related_name='ELA_authActingID')
    empActingAuthStatus = models.BooleanField(default=False)


class EmployeeHierarchy(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    # For CL/RH:
    empHeadAuthID1 = models.ForeignKey(EmployeeLeaveAuthority, related_name='EH_empAuthID1')
    # For Other types of Leaves:
    empHeadAuthID2 = models.ForeignKey(EmployeeLeaveAuthority, related_name='EH_empAuthID2')


class Holidays(models.Model):
    HolidayType = models.CharField(max_length=3)
    HolidayFrom = models.DateField()
    HolidayTo = models.DateField()

fusion/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from fusion.models import *


LEAVE_TYPE = (
    ('CL', 'Casual Leave'),
    ('COL', 'Commuted Leave'),
    ('EL', 'Earned Leave'),
    ('RH', 'Restricted Holiday'),
    ('SCL', 'Special Casual Leave'),
    ('VL', 'Vacation Leave'),
)


class LoginForm(forms.Form):
    lf_UserEmail = forms.EmailField(max_length=50, widget=forms.TextInput(attrs={'type': 'email', 'placeholder': 'employee@iiitdmj.ac.in'}))
    lf_UserPassword = forms.CharField(widget=forms.TextInput(attrs={'type': 'password', 'placeholder': 'Password'}))

    def clean_message(self):
        useremail = self.cleaned_data.get('lf_UserEmail')
        userpassword = self.cleaned_data.get('lf_UserPassword')
        dbUser = get_object_or_404(Employee, empEmail=useremail, empPassword=userpassword)

        print(dbUser.pk)

        if not dbUser.pk:
            raise forms.ValidationError('The Username or Password is Incorrect!')

        return dbUser


class LeaveApplicationForm(forms.Form):
    laf_LeaveType = forms.Select(choices=LEAVE_TYPE)

fusion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .forms import *
from .models import *

loginform = LoginForm()

def index(request):
    context = {}

    return render(request, "fusion/general/index1.html", context)
    # return render(request, "fusion/general/index.html", context)


def dashboard(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    leave_type = ['Casual Leave', 'Commuted Leave', 'Earned Leave', 'Restricted Holiday', 'Sp. Casual Leave',
                  'Vacation Leave']

    context = {'leave_type': leave_type,
               'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/dashboard/dashboard.html", context)


def profile(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/eisModule/profile.html", context)


def leave(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    leave_type = ['Casual Leave', 'Commuted Leave', 'Earned Leave', 'Restricted Holiday', 'Sp. Casual Leave',
                  'Vacation Leave']

    context = {'leave_type': leave_type,
               'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/leaveModule/leave.html", context)


def leaveApplicationForm(request):
    if loginform.is_valid():
        dbUser = loginform.clean_message()
        userID = str(dbUser.pk)

        context = {'user_name': userID,
                   'loginform': loginform,
                   'dbUser': dbUser
                   }

        leaveapplicationform = leaveApplicationForm(request.POST)

    return render(request, "fusion/leaveModule/leave.html", context)


def login(request):
    loginform = LoginForm(request.POST)

    if loginform.is_valid():
        dbUser = loginform.clean_message()
        userID = str(dbUser.pk)

        context = {'user_name': userID,
                   'loginform': loginform,
                   'dbUser': dbUser
                   }
        return redirect('/fusion/dashboard/' + context['user_name'], context)

    else:
        context = {'loginform': loginform}
        return render(request, 'fusion/general/login.html', context)


def visitorhostel(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/vhModule/visitorhostel.html', context)


def placement(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/placementModule/placement.html', context)


def phc(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/phcModule/phc.html', context)


def temp(request):
    return render(request, 'fusion/general/base.html', {})

fusion/templates/fusion/general/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fusion!
        {% block title %}{% endblock %}
    </title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/semantic-ui/components/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/semantic-ui/components/icon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/css/semantic.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/css/mediaquery.css' %}">

    {% block css %}
    {% endblock %}

</head>

{% comment %}style="background-color: rgba(189, 189, 189, 0.1);"{% endcomment %}
<body id="body">

{% block body %}
    {% block navBar %}
    {% endblock %}
{% endblock %}

</body>

<script type="text/javascript" src="{% static 'fusion/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fusion/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fusion/js/dropdown.js' %}"></script>
<script type="text/javascript" src="{% static 'fusion/js/tab.js' %}"></script>

    <script>
        $(document).ready(function(){
            $('.ui.accordion').accordion('refresh');

            $('.ui.sidebar')
                //.sidebar('toggle')
                .sidebar('attach events', '#navbar #sidebartrigger')
                .sidebar('setting', 'transition', 'overlay')
            ;
        });
    </script>

{% block javascript %}
{% endblock %}

</html>

fusion/templates/fusion/general/carousel.html
{% load static %}

{% block carousel %}
    {% comment %}
        The Carousel starts here!
    {% endcomment %}

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="" style="height: 25%;">
                <div class="carousel-caption">
                    <h3>Employee Leave Module</h3>
                    <p>Applying for leave was never so much fun!</p>
                </div>
            </div>

            <div class="item">
                <img src="" style="height: 25%;">
                <div class="carousel-caption">
                    <h3>Visitor Hostel Module</h3>
                    <p>Kya aapne kabhi online Visitor Hostel search kia hai?</p>
                </div>
            </div>

            <div class="item">
                <img src="" style="height: 25%;">
                <div class="carousel-caption">
                    <h3>Mess Module</h3>
                    <p>The source of Food Poisoning!</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% comment %}
        The Carousel ends here!
    {% endcomment %}
{% endblock %}

fusion/templates/fusion/general/index.html
<head>
    <title>
        ERP!
    </title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/css/cover.css' %}">

</head>

<body>
    <div class="site-wrapper">
        <div class="site-wrapper-inner">
            <div class="cover-container">
                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">
                            Fusion!
                        </h3>

                        <nav>
                            <ul class="nav masthead-nav">
                                <li class="active"><a href="{% url 'fusion:index' %}">Home</a></li>
                                <li>
                                    <a href="{% url 'fusion:login' %}">Log in</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="inner cover">
                    <h1 class="cover-heading">Fusion!</h1>
                    <p class="lead">
                        An Intranet Institute <br> Enterprise Resource Planning Web Application!
                    </p>
                    <p class="lead">
                        <a href="{% url 'fusion:login' %}" class="btn btn-lg btn-default">Log in</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    {% block carousel %}
        {% include 'fusion/general/carousel.html' %}
    {% endblock %}

</body>

<script type="text/javascript" src="{% static 'fusion/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fusion/bootstrap/js/bootstrap.min.js' %}"></script>

fusion/templates/fusion/general/index1.html
{% extends 'fusion/../fusion/general/base.html' %}
{% load static %}


{% block title %}
    Home
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'fusion/css/site.css' %}">
    <style type="text/css">

        .hidden.menu {
            display: none;
        }

        .masthead.segment {
            min-height: 700px;
            padding: 1em 0em;
        }
        .masthead .logo.item img {
            margin-right: 1em;
        }
        .masthead .ui.menu .ui.button {
            margin-left: 0.5em;
        }
        .masthead h1.ui.header {
            margin-top: 3em;
            margin-bottom: 0em;
            font-size: 4em;
            font-weight: normal;
        }
        .masthead h2 {
            font-size: 1.7em;
            font-weight: normal;
        }

        .ui.vertical.stripe {
            padding: 8em 0em;
        }
        .ui.vertical.stripe h3 {
            font-size: 2em;
        }
        .ui.vertical.stripe .button + h3,
        .ui.vertical.stripe p + h3 {
            margin-top: 3em;
        }
        .ui.vertical.stripe .floated.image {
            clear: both;
        }
        .ui.vertical.stripe p {
            font-size: 1.33em;
        }
        .ui.vertical.stripe .horizontal.divider {
            margin: 3em 0em;
        }

        .team.stripe.segment {
            padding: 0em;
        }
        .team.stripe.segment .grid .column {
            padding-top: 5em;
            padding-bottom: 5em;
        }

        .footer.segment {
            padding: 5em 0em;
        }

        .secondary.pointing.menu .toc.item {
            display: none;
        }

        @media only screen and (max-width: 700px) {
            .ui.fixed.menu {
                display: none !important;
            }
            .secondary.pointing.menu .item,
            .secondary.pointing.menu .menu {
                display: none;
            }
            .secondary.pointing.menu .toc.item {
                display: block;
            }
            .masthead.segment {
                min-height: 350px;
            }
            .masthead h1.ui.header {
                font-size: 2em;
                margin-top: 1.5em;
            }
            .masthead h2 {
                margin-top: 0.5em;
                font-size: 1.5em;
            }
        }


    </style>
{% endblock %}

{% block body %}
    <!-- Following Menu -->
    <div class="ui massive top fixed menu transition hidden">
        <div class="ui container">
            <a class="active item">Home</a>

            <div class="right menu">
                <div class="item">
                    <a class="ui button" href="{% url 'fusion:login' %}">
                        Log in
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Page Contents -->
    <div class="pusher">
    <div class="ui inverted vertical masthead center aligned segment">

        <div class="ui container">
            <div class="ui large secondary inverted pointing menu">

                <a class="active item">Home</a>

                <div class="right item">
                    <a class="ui inverted button" href="{% url 'fusion:login' %}">
                        Log in
                    </a>
                </div>
            </div>
        </div>

        <div class="ui text container">
            <h1 class="ui inverted header">
                Fusion!
            </h1>

            <h3>
                An Intranet Institute
                <br>
                Enterprise Resource Planning Application!
            </h3>

            <!--TODO-->

            <a class="ui primary large button" href="{% url 'fusion:login' %}">
                Log in
                <i class="right arrow icon"></i>
            </a>
        </div>

    </div>

    {% comment %}
        The Second segment starts here!
    {% endcomment %}
    <div class="ui vertical stripe segment" style="background-color: #FFF;">
        <div class="ui text container">
            <h3 class="ui header">
                Missing out all the fun?
            </h3>

            <p>
                What are you waiing for?
                Don't you wanna be part of something greater than everything?
                So, just Sign up?
                But, beware with great power comes great responsibilities.
                Sign up only when you are ready . . .
            </p>

            <h4 class="ui horizontal header divider">
                <span>Sign up</span>
            </h4>

            <h3 class="ui header">
                Can't Signup? Where's the link?
            </h3>

            <p>
                Yes I know, you probably feel disappointed that you are not worthy.
                <br> Yup, that is true XD
                <br> Well, the sign up is actually disabled to avoid fakes. So you'll need the administrator to create an account for you.
            </p>
        </div>
    </div>
    {% comment %}
        The Second Segment ends here!
    {% endcomment %}


    <div class="ui inverted vertical footer segment">
        <div class="ui divider"></div>

        <div class="ui container">
            <div class="ui stackable inverted divided equal height stackable grid">

                <!--TODO-->
                <div class="six wide column">
                    <img class="ui tiny image right floated"
                         alt="ERP!"
                         src=""
                         style="margin-right: 2.5vw;">
                </div>

                <div class="three wide column">
                    <h4 class="ui inverted header">
                        About
                    </h4>

                    <div class="ui inverted link list">
                        <a href="#" class="item">
                            Sitemap
                        </a>
                    </div>
                </div>

                <div class="six wide column">
                    <h4 class="ui inverted header">
                        Team
                    </h4>

                    <div class="ui inverted link list">
                        <a class="item">
                            Kanishka Munshi 2015121
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'fusion/js/sidebar.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusion/js/transition.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusion/js/visibility.js' %}"></script>

    <script>
        $(document)
            .ready(function() {

                // fix menu when passed
                $('.masthead')
                    .visibility({
                        once: false,
                        onBottomPassed: function() {
                            $('.fixed.menu').transition('fade in');
                        },
                        onBottomPassedReverse: function() {
                            $('.fixed.menu').transition('fade out');
                        }
                    })
                ;

                // create sidebar and attach to menu open
                $('.ui.sidebar')
                    .sidebar('attach events', '.toc.item')
                ;

            })
        ;
    </script>
{% endblock %}

{% comment %}
    {% block login %}
        {% include 'fusion/login.html' %}
    {% endblock %}
{% endcomment %}

fusion/templates/fusion/general/login.html
{% extends 'fusion/general/base.html' %}
{% load static %}


{% block title %}
    Login
{% endblock %}

{% block navBar %}
    <div class="ui stackable massive inverted menu">
        <a class="item" href="{% url 'fusion:index' %}">
            <i class="ui active inverted large home icon"></i>
        </a>

        <a class="item" href="{% url 'fusion:index' %}">
            <span>
                Fusion!
            </span>
        </a>
    </div>

    <div class="ui divider"></div>
{% endblock %}

{% block body %}
    <div class="ui raised stackable doubling centered card right floated"
         style="margin: auto;
                margin-top: 7.5%;
                min-width: 360px;">

        <div class="content">
            <img class="ui rounded centered small image"
                 src="{% static 'fusion/img/user.png' %}"
                 style="margin-top: -27.5%;
                        margin-left: 27.5%;"
                 alt="User Image" >

            <div class="ui huge centered header">
                Employee Login
            </div>

        </div>

        <div class="content">
            <form method="post"
                  class="ui form"
                  style="margin-top: 7.5%;
                                    margin-bottom: 3.5%;">
                {% csrf_token %}

                <div class="field">
                    <label for="{{ loginform.lf_UserEmail.id_for_label }}">Email Id:</label>
                    <div class="ui input">
                        {{ loginform.lf_UserEmail }}
                    </div>
                </div>

                <div class="field">
                    <label for="{{ loginform.lf_UserPassword.id_for_label }}">Password:</label>
                    <div class="ui input">
                        {{ loginform.lf_UserPassword }}
                    </div>
                </div>

                <div class="field"
                     style="margin-top: 7.5%;
                                 margin-bottom: 7.5%;">
                    <div class="ui divider"></div>
                </div>

                <div class="field">
                    <button class="ui fluid large primary button"
                            type="submit">
                        Login
                    </button>
                </div>
            </form>

            <div class="ui divider"></div>

            <div class="ui red button">
                <i class="google icon"></i>
                <span class="right floated">Google</span>
            </div>


        </div>

        <div class="extra content">
            <a href="" class="ui inverted text">
                <div class="" style="text-align: center;">
                    Forgot Password?
                </div>
            </a>
        </div>

    </div>
    <div class="ui row">
        <br>
        <br>
        <br>
    </div>
{% endblock %}

fusion/templates/fusion/general/usercard.html
{% load static %}

{% block usercard %}

    {% comment %}The Employee Image Card starts here!{% endcomment %}
    <div class="ui large fluid raised card"
         style="max-width: 320px;">

        <div class="image">
            <img src="{% static 'fusion/img/zlatan.jpg' %}">
        </div>

        <div class="content">
            {% comment %}http://web.iiitdmj.ac.in/~vkjain{% endcomment %}
            <div class="ui large header" href="">
                {{ userFirstName }}
                {{ userLastName }}
                <span class="right floated meta">
                    {{ userDepartment.upper }}
                </span>
            </div>

            <div class="meta">
                <span>
                    {{ userDesignation }}
                </span>
            </div>
        </div>
    </div>
    {% comment %}The Employee Image Card ends here!{% endcomment %}


{% endblock %}