fusion/urls.py
from django.conf.urls import url
from . import views

app_name = 'fusion'

urlpatterns = [
    # fusion/
    url(r'^$', views.index, name='index'),

    # fusion/login/
    url(r'^login$', views.login, name='login'),

    # fusion/leave/<pk>/
    url(r'^leave/(?P<emp_id>[0-9]+)$', views.leave, name='leave'),

    # fusion/visitorhostel/<pk>/
    url(r'^visitorhostel/(?P<emp_id>[0-9]+)$', views.visitorhostel, name='visitorhostel'),

    # fusion/placement/<pk>/
    url(r'^placement/(?P<emp_id>[0-9]+)$', views.placement, name='placement'),

    # fusion/profile/<pk>/
    url(r'^profile/(?P<emp_id>[0-9]+)$', views.profile, name='profile'),

    # fusion/phc/<pk>/
    url(r'^phc/(?P<emp_id>[0-9]+)$', views.phc, name='phc'),

    # fusion/dashboard/<pk>/
    url(r'^dashboard/(?P<emp_id>[0-9]+)$', views.dashboard, name='dashboard'),

    # fusion/temp$/
    url(r'^temp$', views.temp, name='temp'),

]

newProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('fusion.urls')),
    url(r'^fusion/', include('fusion.urls')),
]

fusion/models.py
from django.db import models
from django.core.urlresolvers import reverse

# TODO: These lists are not complete fully!

LEAVETYPE = (
    ('CL', 'Casual Leave'),
    ('COL', 'Commuted Leave'),
    ('EL', 'Earned Leave'),
    ('RH', 'Restricted Holiday'),
    ('SCL', 'Special Casual Leave'),
    ('VL', 'Vacation Leave'),
)

DESIGNATION = (
    ('driver', 'Driver'),
    ('ja', 'Junior Assistant'),
    ('sa', 'Senior Assistant'),
    ('jt', 'Junior Technician'),
    ('st', 'Senior Technician'),
    ('ar', 'Assistant Registrar'),
    ('dr', 'Deputy Registrar'),
    ('rr', 'Registrar'),
    ('Research Engineer', 'Research Engineer'),
    ('Assistant Professor', 'Assistant Professor'),
    ('Associate Professor', 'Associate Professor'),
    ('Professor', 'Professor'),
)

DEPARTMENT = (
    ('iwd', 'IWD'),
    ('et', 'Establishment'),
    ('library', 'Library'),
    ('pc', 'Placement Cell'),
    ('acad', 'Academics'),
    ('ns', 'Natural Science'),
    ('cse', 'CSE'),
    ('ece', 'ECE'),
    ('me', 'ME'),
    ('otd', 'Office of Dean'),
    ('fna', 'Finance and Accounts'),
    ('directorate', 'Directorate'),
)

AUTHDESIGNATION = (
    ('rr', 'Registrar'),
    ('director', 'Director'),
    ('ccc', 'Coordinator Computer Center'),
    ('wi', 'Workshop In-charge'),
    ('headns', 'HOD NS'),
    ('hodcse', 'HOD CSE'),
    ('hodece', 'HOD ECE'),
    ('hodme', 'HOD ME'),
    ('deanacad', 'Dean Academics'),
    ('deanstudents', 'Dean Students'),
    ('deanRSPC', 'Dean RSPC'),
)


class Employee(models.Model):
    empFirstName = models.CharField(max_length=36)
    empLastName = models.CharField(max_length=36)
    empEmail = models.CharField(max_length=36, unique=True)
    empPassword = models.CharField(max_length=36, null=False, default='pass')
    empDesignation = models.CharField(max_length=36, choices=DESIGNATION)
    empDepartment = models.CharField(max_length=36, choices=DEPARTMENT)

    def __str__(self):
        return self.empFirstName + "." + self.empLastName + "." + self.empEmail + "." + self.empPassword + "." + self.empDesignation + "." + self.empDepartment


class EmployeeLeaveBalance(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    empCL = models.IntegerField()
    empCOL = models.IntegerField()
    empEL = models.IntegerField()
    empRH = models.IntegerField()
    empSCL = models.IntegerField()
    empVL = models.IntegerField()


class EmployeeLeaveDetails(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    empLeaveType = models.CharField(max_length=5)
    empLeaveFrom = models.DateField()
    empLeaveTo = models.DateField()
    empLeaveDuration = models.IntegerField()
    empLeaveStatus = models.IntegerField(default=0)
    # Rejected: -1, Approved: 1, Pending: 0


class EmployeeStationLeave(models.Model):
    empLeaveID = models.ForeignKey(EmployeeLeaveDetails, on_delete=models.CASCADE)
    empStationLeave = models.BooleanField(default=False)
    empStationAddress = models.CharField(max_length=150)


class EmployeeLeaveAuthority(models.Model):
    authID = models.IntegerField(primary_key=True, auto_created=True)
    authDesignation = models.CharField(max_length=18, choices=AUTHDESIGNATION)
    authHeadID = models.ForeignKey(Employee, related_name='ELA_authHeadID')
    authActingID = models.ForeignKey(Employee, null=True, related_name='ELA_authActingID')
    empActingAuthStatus = models.BooleanField(default=False)


class EmployeeHierarchy(models.Model):
    empID = models.ForeignKey(Employee, on_delete=models.CASCADE)
    # For CL/RH:
    empHeadAuthID1 = models.ForeignKey(EmployeeLeaveAuthority, related_name='EH_empAuthID1')
    # For Other types of Leaves:
    empHeadAuthID2 = models.ForeignKey(EmployeeLeaveAuthority, related_name='EH_empAuthID2')


class Holidays(models.Model):
    HolidayType = models.CharField(max_length=3)
    HolidayFrom = models.DateField()
    HolidayTo = models.DateField()

fusion/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from fusion.models import *


LEAVE_TYPE = (
    ('CL', 'Casual Leave'),
    ('COL', 'Commuted Leave'),
    ('EL', 'Earned Leave'),
    ('RH', 'Restricted Holiday'),
    ('SCL', 'Special Casual Leave'),
    ('VL', 'Vacation Leave'),
)


class LoginForm(forms.Form):
    lf_UserEmail = forms.EmailField(max_length=50, widget=forms.TextInput(attrs={'type': 'email', 'placeholder': 'employee@iiitdmj.ac.in'}))
    lf_UserPassword = forms.CharField(widget=forms.TextInput(attrs={'type': 'password', 'placeholder': 'Password'}))

    def clean_message(self):
        useremail = self.cleaned_data.get('lf_UserEmail')
        userpassword = self.cleaned_data.get('lf_UserPassword')
        dbUser = get_object_or_404(Employee, empEmail=useremail, empPassword=userpassword)

        print(dbUser.pk)

        if not dbUser.pk:
            raise forms.ValidationError('The Username or Password is Incorrect!')

        return dbUser


class LeaveApplicationForm(forms.Form):
    laf_LeaveType = forms.Select(choices=LEAVE_TYPE)

fusion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .forms import *
from .models import *

loginform = LoginForm()

def index(request):
    context = {}

    return render(request, "fusion/general/index1.html", context)
    # return render(request, "fusion/general/index.html", context)


def dashboard(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    leave_type = ['Casual Leave', 'Commuted Leave', 'Earned Leave', 'Restricted Holiday', 'Sp. Casual Leave',
                  'Vacation Leave']

    context = {'leave_type': leave_type,
               'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/dashboard/dashboard.html", context)


def profile(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/eisModule/profile.html", context)


def leave(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    leave_type = ['Casual Leave', 'Commuted Leave', 'Earned Leave', 'Restricted Holiday', 'Sp. Casual Leave',
                  'Vacation Leave']

    context = {'leave_type': leave_type,
               'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, "fusion/leaveModule/leave.html", context)


def leaveApplicationForm(request):
    if loginform.is_valid():
        dbUser = loginform.clean_message()
        userID = str(dbUser.pk)

        context = {'user_name': userID,
                   'loginform': loginform,
                   'dbUser': dbUser
                   }

        leaveapplicationform = leaveApplicationForm(request.POST)

    return render(request, "fusion/leaveModule/leave.html", context)


def login(request):
    loginform = LoginForm(request.POST)

    if loginform.is_valid():
        dbUser = loginform.clean_message()
        userID = str(dbUser.pk)

        context = {'user_name': userID,
                   'loginform': loginform,
                   'dbUser': dbUser
                   }
        return redirect('/fusion/dashboard/' + context['user_name'], context)

    else:
        context = {'loginform': loginform}
        return render(request, 'fusion/general/login.html', context)


def visitorhostel(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/vhModule/visitorhostel.html', context)


def placement(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/placementModule/placement.html', context)


def phc(request, emp_id):
    employeePK = emp_id
    dbUser = get_object_or_404(Employee, pk=employeePK)
    userFirstName = str(dbUser.empFirstName)
    userLastName = str(dbUser.empLastName)
    userEmail = str(dbUser.empEmail)
    userDepartment = str(dbUser.empDepartment)
    userDesignation = str(dbUser.empDesignation)

    context = {'employeePK': employeePK,
               'userFirstName': userFirstName,
               'userLastName': userLastName,
               'userEmail': userEmail,
               'userDesignation': userDesignation,
               'userDepartment': userDepartment,
               'loginform': loginform,
               }

    return render(request, 'fusion/phcModule/phc.html', context)


def temp(request):
    return render(request, 'fusion/general/base.html', {})

fusion/templates/fusion/dashboard/alerts.html
{% load static %}

{% block alerts %}
    {% comment %}The Alerts start here!{% endcomment %}
    <div class="ui fluid card" style="padding-top: 12px; padding-bottom: 24px;">
        <a class="ui top attached black label">
            <span class="ui inverted header">
                Alerts
            </span>
            <i class="setting icon right floated"></i>
            <i class="chevron up icon right floated"></i>
        </a>

        <div class="content alerts" style="max-height: 75vh; overflow-y: auto;">
            <div class="ui animated list">
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="content">
                        <div class="right floated"><i class="calendar icon"></i>12.04.2014</div>
                        <div class="header">
                            <i class="ban circle teal circular icon"></i>
                            4 system errors
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% comment %}The Alerts ends here!{% endcomment %}
{% endblock %}

fusion/templates/fusion/dashboard/modules.html
{% load static %}

{% block modules %}
{% comment %}The Modules start here!{% endcomment %}
    <div class="stackable doubling ui internally celled grid">
        <div class="column">
            <div class="ui fluid card" style="padding-top: 12px; padding-bottom: 24px; max-width: 18vw;">
                <a class="ui top attached black label">
                    <span class="ui inverted header">Modules</span>
                    <i class="setting icon right floated"></i>
                    <i class="chevron up icon right floated" id="toggleIcon" onclick="toggleContent()"></i>
                </a>

                <div class="content modulesContent">
                    <div class="ui two column stackable doubling grid">
                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}

                        {% comment %}A single modules row starts here!{% endcomment %}
                        <div class="row">
                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="column">
                                <a class="ui large label" href="{% url 'fusion:leave' employeePK %}">
                                    <div class="ui centered grid">
                                        <div class="row">
                                            <i class="ui plane centered icon big"></i>
                                        </div>

                                        <div class="row">
                                            <span class="ui sub header">Leave Module</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% comment %}A single modules row ends here!{% endcomment %}
                    </div>
                </div>

{% comment %}
                <a class="ui bottom attached blue label">
                    <i class="right arrow icon right floated"></i>
                </a>
{% endcomment %}
            </div>
        </div>
    </div>
    {% comment %}The Modules End here!{% endcomment %}
{% endblock %}

fusion/templates/fusion/dashboard/navbar.html
{% load static %}

{% block navBar %}
    {% include 'fusion/dashboard/sidenavbar.html' %}

    <div>
        <div class="ui stackable massive inverted top attached menu" id="navbar">
            <a class="item" id="sidebartrigger">
                <i class="sidebar icon"></i>
            </a>
            <a class="item" href="{% url 'fusion:index' %}" >
                <span>
                    Fusion!
                </span>
            </a>

            <a class="item" href="{% url 'fusion:dashboard' employeePK %}">
                <i class="ui active inverted large home icon"></i>
                Dashboard
            </a>

            <div class="right inverted menu">
                <a class="item" href="{% url 'fusion:profile' employeePK %}">
                    <img class="ui avatar image" src="{% static 'fusion/img/zlatan.jpg' %}">
                    Atul Gupta
                </a>

                <div class="ui dropdown icon item">
                    <i class="settings icon"></i>
                    <div class="menu">
                        <div class="item">
                            <i class="dropdown icon"></i>
                            <span class="text">New</span>
                            <div class="menu">
                                <div class="item">Document</div>
                                <div class="item">Image</div>
                            </div>
                        </div>
                        <div class="item">
                            Open...
                        </div>
                        <div class="item">
                            Save...
                        </div>
                        <div class="item">Edit Permissions</div>
                        <div class="divider"></div>
                        <div class="header">
                            Export
                        </div>
                        <div class="item">
                            Share...
                        </div>
                    </div>

                </div>

                <div class="item">
                    <i class="icon mail"></i>
                    <div class="ui red label">22</div>
                </div>

                <div class="item">
                    <i class="alarm icon"></i>
                    <div class="ui teal label">22</div>
                </div>

                <a class="right item" href="{% url 'fusion:index' %}">
                    <i class="ui inverted sign out icon"></i>
                    Logout
                </a>

            </div>
        </div>

        <div class="ui divider"></div>


    {% block data%}
    {% endblock %}



    </div>
{% endblock %}

fusion/templates/fusion/dashboard/sidenavbar.html
{% load static %}

{% block sidenav %}
    <div class="ui sidebar inverted vertical menu">
        <div class="ui doubling stackable grid container">

            <div class="ui inverted centered raised item"></div>

            {% comment %}The User Item starts here!{% endcomment %}
            <div class="ui inverted centered raised item">
                <img src="{% static 'fusion/img/zlatan.jpg' %}" class="ui small circular centered image">

                <br>

                <div class="ui bottom attached inverted" style="text-align: center;">
                    <h2 class="ui inverted header">Dr. Atul Gupta</h2>
                    <span class="ui inverted meta">Associate Professor</span>
                </div>

            </div>
            {% comment %}The User Item ends here!{% endcomment %}

            <div class="ui divider inverted"></div>

            {% comment %}The Modules Accordian starts here!{% endcomment %}
            <div class="ui vertical inverted accordion fluid menu" style="margin-bottom: 24px;">
                <div class="item">
                    <a class="active title">
                        <i class="dropdown icon"></i>
                        <span class="ui inverted header">
                            Modules
                        </span>
                    </a>
                    <div class="active content">
                        <div class="link items">
                            <a class="item" href="{% url 'fusion:leave' employeePK %}">
                                <h4>Leave Module</h4>
                            </a>

                            <a class="item" href="{% url 'fusion:visitorhostel' employeePK %}">
                                <h4>Visitor Hostel Module</h4>
                            </a>

                            <a class="item" href="{% url 'fusion:placement' employeePK %}">
                                <h4>Placement Module</h4>
                            </a>

                            <a class="item" href="{% url 'fusion:leave' employeePK %}">
                                <h4>Mess Module</h4>
                            </a>

                             <a class="item" href="{% url 'fusion:leave' employeePK %}">
                                <h4>phc  Module</h4>
                            </a>

                        </div>
                    </div>
                </div>
            </div>
            {% comment %}The Modules Accordian ends here!{% endcomment %}

            {% comment %}The Profile Item starts here!{% endcomment %}
            <a class="centered raised item" href="{% url 'fusion:profile' employeePK %}">
                <span class="inverted header">Profile</span>
                <i class="large inverted user icon right floated"></i>
            </a>
            {% comment %}The email Item ends here!{% endcomment %}

            {% comment %}The email Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Emails</span>
                <i class="large inverted mail icon right floated"></i>
            </div>
            {% comment %}The email Item ends here!{% endcomment %}

            {% comment %}The Webpage Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Webpage</span>
                <i class="large inverted external icon right floated"></i>
            </div>
            {% comment %}The Webpage Item ends here!{% endcomment %}

            {% comment %}The Activity Log Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Activity Log</span>
                <i class="large inverted area chart icon right floated"></i>
            </div>
            {% comment %}The Activity Log Item ends here!{% endcomment %}

            {% comment %}The Logout Item starts here!{% endcomment %}
            <div class="centered raised item">
                <span class="inverted header">Logout</span>
                <i class="large inverted sign out icon right floated"></i>
            </div>
            <div class="item"></div>
            {% comment %}The Logout Item ends here!{% endcomment %}

        </div>
    </div>

{% endblock %}